## Introduction to the extended version of DiCE (Diverse Counterfactual Explanations)

[Mothilal et al. (2020)](https://dl.acm.org/doi/10.1145/3351095.3372850) introduce their method of generating counterfactual explanations considering _feasibility_, and _diversity_. [Guidotti and Ruggieri (2021)](https://link.springer.com/chapter/10.1007/978-3-030-88942-5_28), claim counterfactual explanations to be robust they should be similar for similar instances when they explain. In this study, in a search to improve the quality and reliability of the counterfactual explanations _robustness_ is found to be helpful and it also introduced in the optimization function.

DiCE-Extended is built upon the [DiCE (Diverse Counterfactual Explanations)](https://github.com/interpretml/DiCE) [(Mothilal et al. 2020)](https://dl.acm.org/doi/10.1145/3351095.3372850) framework by introducing a robustness term in the optimization function.

## Manipulated Optimization Function

The core enhancement in DiCE-Extended is the manipulated optimization function, designed to balance proximity, diversity, and feasibility of counterfactuals. The function is formulated as:

<a id="equation-1"></a>
\begin{equation}
\tag{1}
C(x) = \underset{c_1, ..., c_k}{\text{arg min}}
\frac{1}{2} \sum_{i=1}^{k} yloss(f(c_i), y) +
\frac{\lambda_1}{k} \sum_{i=1}^{k} dist(c_i, x) -
\lambda_2 \cdot dpp\_diversity(c_1, ..., c_k) -
\frac{\lambda_3}{k} \sum_{i=1}^{k} robustness(c_i, c_i')
\end{equation}

- **Proximity Loss**: The first term that averages the distance between generated counterfactuals and the original input ensure the counterfactuals to be as close as possible to the original input.
- **Diversity Loss**: Diversity of the counterfactual explanations is aquired by determinental point process of which loss is represented by the second term and it ensures that _k_ number of counterfactual explanations are generated.
- **Robustness Loss**: [Guidotti (2024)](https://link.springer.com/article/10.1007/s10618-022-00831-6) defines robustness as necessity of similar instances being explained by similar counterfactual explanations such that if $b(x_1)=b(x_2)=y$ then an explainer $f$ should generate counterfactuals $c_1$ and $c_2$ that are similar and can explain $x_1$ and $x_2$. The robustness term that is based on [Dice-Sørensen Coefficient](https://en.wikipedia.org/wiki/Dice-S%C3%B8rensen_coefficient), is adopted from [Bonasera and Carrizosa (2024)](
https://doi.org/10.48550/arXiv.2407.00843).

\begin{equation}
\tag{2}
Robustness(c_i, c_i') = \frac{2 * \lvert c_i \cap c_i' \rvert}{\lvert c_i \rvert + \lvert c_i' \rvert}
\end{equation}


By adjusting the weights $\lambda_1$, $\lambda_2$, $\lambda_3$ counterfactual explanations can be customised by specific needs.

## Metrics and Sensitivity Analysis for Dice Extended


### 1. Robustness Metrics

#### Dice-Sørensen Coefficient

To evaluate robustness, the Dice-Sørensen coefficient measures the similarity between counterfactuals c1 and
c2 generated for similar input instances x1 and x2:

\begin{equation}
\tag{3}
Robustness(c_1, c_2) = \frac{2 * \lvert c_1 \cap c_2 \rvert}{\lvert c_1 \rvert + \lvert c_2 \rvert}
\end{equation}

where:
- $ c_1 $ and $ c_2 $ are binary vectors,
- $ \lvert c_1 \cap c_2 \rvert $: The number of shared (overlapping) features between c1 and c2,
- $ \lvert c_1 \rvert $ and $ \lvert c_2 \rvert $: The total number of features in each counterfactual.

#### Input Perturbation and Stability

Stability under input perturbation measures the solution variance when slight perturbations are introduced
to the input instance. The procedure includes the following steps:

1) **Apply Gaussian Noise:** Perturb the input $x$ by adding Gaussian noise $\delta$ to create perturbed inputs
$x'$:

\begin{equation}
\tag{4}
x' = x + \delta, \quad \delta \sim \mathcal{N}(0, \sigma^2)
\end{equation}

where $\sigma$ is the standard deviation of the noise (e.g., $\sigma = 0.01$).

2) **Generate Counterfactuals:** Generate counterfactual explanations $c_i$ for the original input $x$ and $c_i'$ for the perturbed input $x'$.

3) **Measure Stability:** Compare counterfactuals using a distance metric, such as the Euclidean distance:

\begin{equation}
\tag{5}
Stability = \frac{1}{n} \sum_{i=1}^{n} dist(c_i, c_i')
\end{equation}

where:

\begin{equation}
\tag{6}
dist(c_i, c_i') = \sqrt{\sum_{j=1}^{d} (c_{ij} - c_{ij}')^2}
\end{equation}

$n$ is the total number of input instances, $c_i$ is the counterfactual for the original input, and $c_i'$ is the counterfactual for the perturbed input.

### 2. Counterfactual Quality Measures

#### Fidelity

Fidelity measures how often generated counterfactuals successfully change the model’s prediction:

\begin{equation}
\tag{7}
Fidelity = \frac{\sum_{i=1}^{n} \mathbf{1}(f(c_i) = y_{desired})}{n}
\end{equation}

where:

- $f$: Prediction model,
- $c_i$: Counterfactual instance,
- $y_{desired}$: Target output class,
- $n$: Total number of counterfactuals.

#### Proximity

Proximity measures the average distance between counterfactuals $c_i$ and the original inputs $x_i$:

\begin{equation}
\tag{8}
Proximity = \frac{1}{n} \sum_{i=1}^{n} dist(x_i, c_i)
\end{equation}

The Manhattan distance can be used for simplicity:

\begin{equation}
\tag{9}
dist(x_i, c_i) = \sum_{j=1}^{d} \lvert x_{ij} - c_{ij} \rvert
\end{equation}

#### Diversity

Diversity measures how dissimilar the counterfactuals $c_1, c_2, c_3,\ldots,c_k$ are among themselves:

\begin{equation}
\tag{10}
Diversity = \frac{1}{k(k-1)}\sum_{i_1}^{k}\sum_{j \neq i}^{} dist(c_i, c_j)
\end{equation}

where $k$ is the number of counterfactuals.

### 3. Sensitivity Analysis

#### Objective Function with Weights

The modified loss function in DiCE-Extended is defined as in the [equation 1](#equation-1) where:

- $yloss(f(c_i), y)$: Prediction loss for counterfactual instance $c_i$ relative to the desired outcome $y$,
- $dist(c_i, x)$: Distance metric (e.g., Euclidean or Manhattan) between the counterfactual c_i and the original input $x$,
- $dpp\_diversity(c_1,\ldots,c_k)$: Diversity loss term based on Determinantal Point Process (DPP),
- $Robustness(c_i,c_i')$: Robustness loss measuring similarity of counterfactuals under perturbations.

  The weights $\lambda_1, \lambda_2, \lambda_3$ control the balance between proximity, diversity, and robustness, respectively.

#### Sensitivity Analysis

To perform sensitivity analysis:

1) Vary the weights $\lambda_1, \lambda_2, \lambda_3$ systematically while ensuring:

\begin{equation}
\tag{11}
\lambda_1 + \lambda_2 + \lambda_3 = 1 (for normalization).
\end{equation}

2) Track the changes in the following metrics:

\begin{equation}
\tag{12}
P(\lambda_1, \lambda_2, \lambda_3) = Proximity,
\end{equation}

\begin{equation}
\tag{13}
D(\lambda_1, \lambda_2, \lambda_3) = Diversity,
\end{equation}

\begin{equation}
\tag{14}
R(\lambda_1, \lambda_2, \lambda_3) = Robustness,
\end{equation}

3) Measure the relationship between these metrics and the weights.

In [1]:
import sys
dice_path = "/Users/volk/Documents/bau24-25/thesis/repos/DiCE-X"
sys.path.insert(0, dice_path)

In [2]:
from dice_ml_x.utils import helpers

In [3]:
%load_ext autoreload
%autoreload 2

In [ ]:
from dice_ml_x.benchmarking import Benchmarking
datasets = ["compas-recidivism", "adult-income", "lending-club", "german-credit"]
backends = ["sklearn", "PYT", "TF2"]
methods =['gaussian']
benchmarking = Benchmarking(datasets=datasets,
                            backends=backends,
                            perturbation_methods=methods)
benchmarking.load_and_train(batch_size=16)

""" At the end of the load and train process a dictionary containing the training and counterfactual
generation history is saved following object can be found in the results object:
"""

Benchmarking:   0%|          | 0/12 [00:00<?, ?it/s]

the dataset is : compas-recidivism, the backend is : sklearn, the method is gaussian

100%|██████████| 1/1 [00:10<00:00, 10.21s/it]
Benchmarking:   8%|▊         | 1/12 [00:10<01:54, 10.40s/it, dataset=compas-recidivism, backend=sklearn, method=gaussian]

the dataset is : compas-recidivism, the backend is : PYT, the method is gaussian

/Users/volk/Documents/bau24-25/thesis/repos/DiCE-X/dice_ml_x/explainer_interfaces/dice_pytorch.py:407: UserWarning: torch.searchsorted(): input value tensor is non-contiguous, this will lower the performance due to extra data copy when converting non-contiguous tensor to contiguous, please use contiguous input value tensor if possible. This message will only appear once per program. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/BucketizationUtils.h:34.)
  binned_indices = torch.bucketize(col_vals, edges, right=False) - 1
100%|██████████| 1/1 [00:02<00:00,  2.69s/it]
Benchmarking:  17%|█▋        | 2/12 [00:14<01:06,  6.62s/it, dataset=compas-recidivism, backend=PYT, method=gaussian]

Diverse Counterfactuals found! total time taken: 00 min 02 sec
the dataset is : compas-recidivism, the backend is : TF2, the method is gaussian

Benchmarking:  25%|██▌       | 3/12 [00:46<02:45, 18.37s/it, dataset=compas-recidivism, backend=TF2, method=gaussian]

Diverse Counterfactuals found! total time taken: 00 min 30 sec
the dataset is : adult-income, the backend is : sklearn, the method is gaussian

100%|██████████| 1/1 [00:49<00:00, 49.07s/it]
Benchmarking:  33%|███▎      | 4/12 [01:39<04:14, 31.84s/it, dataset=adult-income, backend=sklearn, method=gaussian]

the dataset is : adult-income, the backend is : PYT, the method is gaussian

100%|██████████| 1/1 [00:07<00:00,  7.14s/it]
Benchmarking:  42%|████▏     | 5/12 [01:53<02:57, 25.42s/it, dataset=adult-income, backend=PYT, method=gaussian]

Diverse Counterfactuals found! total time taken: 00 min 06 sec
the dataset is : adult-income, the backend is : TF2, the method is gaussian

Benchmarking:  50%|█████     | 6/12 [02:45<03:27, 34.57s/it, dataset=adult-income, backend=TF2, method=gaussian]

Diverse Counterfactuals found! total time taken: 00 min 43 sec
the dataset is : lending-club, the backend is : sklearn, the method is gaussian

100%|██████████| 1/1 [01:50<00:00, 110.42s/it]
Benchmarking:  58%|█████▊    | 7/12 [04:40<05:04, 60.88s/it, dataset=lending-club, backend=sklearn, method=gaussian]

the dataset is : lending-club, the backend is : PYT, the method is gaussian

100%|██████████| 1/1 [00:17<00:00, 17.31s/it]
Benchmarking:  67%|██████▋   | 8/12 [05:06<03:19, 49.76s/it, dataset=lending-club, backend=PYT, method=gaussian]

Diverse Counterfactuals found! total time taken: 00 min 16 sec
the dataset is : lending-club, the backend is : TF2, the method is gaussian

Benchmarking:  75%|███████▌  | 9/12 [08:37<05:00, 100.23s/it, dataset=lending-club, backend=TF2, method=gaussian]

Diverse Counterfactuals found! total time taken: 03 min 20 sec
the dataset is : german-credit, the backend is : sklearn, the method is gaussian

100%|██████████| 1/1 [03:37<00:00, 217.61s/it]
Benchmarking:  83%|████████▎ | 10/12 [12:15<04:33, 136.52s/it, dataset=german-credit, backend=sklearn, method=gaussian]

the dataset is : german-credit, the backend is : PYT, the method is gaussian

WARNING:root: MAD for feature number_of_existing_credits_at_this_bank is 0, so replacing it with 1.0 to avoid error.
WARNING:root: MAD for feature number_of_people_being_liable_to_provide_maintenance_for is 0, so replacing it with 1.0 to avoid error.
100%|██████████| 1/1 [00:10<00:00, 10.88s/it]
Benchmarking:  92%|█████████▏| 11/12 [12:26<01:38, 98.16s/it, dataset=german-credit, backend=PYT, method=gaussian]

Diverse Counterfactuals found! total time taken: 00 min 08 sec

WARNING:root: MAD for feature number_of_existing_credits_at_this_bank is 0, so replacing it with 1.0 to avoid error.
WARNING:root: MAD for feature number_of_people_being_liable_to_provide_maintenance_for is 0, so replacing it with 1.0 to avoid error.

the dataset is : german-credit, the backend is : TF2, the method is gaussian

Benchmarking: 100%|██████████| 12/12 [13:28<00:00, 67.40s/it, dataset=german-credit, backend=TF2, method=gaussian]

Diverse Counterfactuals found! total time taken: 00 min 59 sec

' At the end of the load and train process a dictionary containing the training and counterfactual\ngeneration history is saved following object can be found in the results object:\n'

In [13]:
benchmarking.results

{'compas-recidivism': {'sklearn': {'accuracy': 0.5714285714285714,
   'cfs': {'gaussian':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0    Male  27.0           0.0  African-American               F             1
    0    Male  28.0           0.0  African-American               F             1
    0    Male  26.0           0.0  African-American               F             1
    0  Female  26.0           0.0         Caucasian               F             1
    0    Male  22.7           0.0  African-American               F             1},
   'input_instance': {'gaussian':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F},
   'time': {'gaussian': 10.215321063995361},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['c_charge_degree', 'race', 'sex'], dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.6579476861167002,
   'cfs': {'gaussian':       sex   age  priors_count       race c_charge_degree  twoyearrecid
    0  Female  18.0           0.0  Caucasian               M         0.554
    1  Female  26.6           6.2  Caucasian               F         0.557
    2  Female  18.0          15.0  Caucasian               F         0.651
    3  Female  26.9          22.5  Caucasian               F         0.678
    4  Female  21.0          30.3  Caucasian               F         0.726},
   'input_instance': {'gaussian':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F},
   'time': {'gaussian': 2.691739082336426},
   'model_path': 'benchmarking_artefact/compas-recidivism_PYT_model.pth'},
  'TF2': {'accuracy': 0.6549295783042908,
   'cfs': {'gaussian':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0  Female  18.0           0.0         Caucasian               M         0.737
    1    Male  27.1           7.6         Caucasian               M         0.706
    2    Male  31.8           0.0         Caucasian               M         0.699
    3    Male  43.0           0.0  African-American               M         0.731
    4    Male  70.3           0.0  African-American               M         0.747},
   'input_instance': {'gaussian':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F},
   'time': {'gaussian': 30.9517502784729},
   'model_path': 'benchmarking_artefact/compas-recidivism_TF2_model'}},
 'adult-income': {'sklearn': {'accuracy': 0.8183632734530938,
   'cfs': {'gaussian':    age      workclass     education marital_status     occupation   race  \
    0   23  Other/Unknown         Assoc        Married  Other/Unknown  White
    0   17  Other/Unknown     Bachelors        Married        Service  White
    0   17     Government  Some-college       Divorced   Professional  White
    0   17     Government     Doctorate        Widowed  Other/Unknown  White
    0   17  Other/Unknown     Doctorate      Separated   Professional  White

      gender  hours_per_week  income
    0   Male              40       1
    0   Male              40       1
    0   Male              40       1
    0   Male              40       1
    0   Male              40       1  },
   'input_instance': {'gaussian':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  },
   'time': {'gaussian': 49.07638478279114},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['education', 'gender', 'marital_status', 'occupation', 'race',
          'workclass'],
         dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.8335636419468755,
   'cfs': {'gaussian':    age      workclass     education marital_status     occupation   race  \
    0   20        Private     Bachelors      Separated  Other/Unknown  White
    1   24        Private  Some-college      Separated          Sales  Other
    2   18  Other/Unknown     Bachelors        Widowed    Blue-Collar  White
    3   53        Private         Assoc         Single  Other/Unknown  White
    4   90        Private  Some-college         Single  Other/Unknown  White

       gender  hours_per_week  income
    0    Male              31   0.807
    1    Male              42   0.795
    2    Male              41   0.782
    3    Male              40   0.668
    4  Female              40   0.755  },
   'input_instance': {'gaussian':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  },
   'time': {'gaussian': 7.1413209438323975},
   'model_path': 'benchmarking_artefact/adult-income_PYT_model.pth'},
  'TF2': {'accuracy': 0.8343313336372375,
   'cfs': {'gaussian':     age      workclass     education marital_status     occupation   race  \
    0  20.0  Other/Unknown   Prof-school         Single  Other/Unknown  White
    1  21.0        Private       HS-grad        Widowed  Other/Unknown  White
    2  17.0  Self-Employed  Some-college       Divorced  Other/Unknown  White
    3  21.0     Government  Some-college         Single  Other/Unknown  Other
    4  32.0  Self-Employed  Some-college         Single  Other/Unknown  White

       gender  hours_per_week  income
    0    Male            26.0   0.593
    1    Male            41.0   0.772
    2    Male            37.0   0.607
    3  Female            40.0   0.791
    4    Male            53.0   0.874  },
   'input_instance': {'gaussian':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  },
   'time': {'gaussian': 43.72406721115112},
   'model_path': 'benchmarking_artefact/adult-income_TF2_model'}},
 'lending-club': {'sklearn': {'accuracy': 0.8238700742792395,
   'cfs': {'gaussian':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 5                    8       150000.0          F
    0                 4                   12       185000.0          F
    0                 0                   12       185000.0          D
    0                 5                    9       200000.0          C
    0                 0                    2         4080.0          A

       credit_history         purpose      home addr_state  loan_status
    0            12.1        purchase  MORTGAGE         NJ            0
    0            14.2            debt  MORTGAGE         MI            0
    0            17.4  small_business  MORTGAGE         NJ            0
    0            14.2            debt  MORTGAGE         OK            0
    0             3.0        purchase     OTHER         FL            0  },
   'input_instance': {'gaussian':        employment_years  num_open_credit_acc  annual_income loan_grade  \
    24355                 5                   12       175000.0          F

           credit_history   purpose      home addr_state
    24355            16.5  purchase  MORTGAGE         PA  },
   'time': {'gaussian': 110.42094278335571},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['addr_state', 'home', 'loan_grade', 'purpose'], dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.8291577489613496,
   'cfs': {'gaussian':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 0                    6       149156.2          D
    1                10                   12       182472.9          A
    2                10                   14         4080.0          A
    3                10                   36       183518.6          A
    4                10                   11       269372.2          A

       credit_history   purpose      home addr_state  loan_status
    0            51.0  purchase  MORTGAGE         VT        0.401
    1            57.1  purchase      RENT         VA        0.260
    2            17.2  purchase      RENT         VT        0.246
    3            16.1  purchase      RENT         VT        0.251
    4            16.3  purchase      RENT         VA        0.277  },
   'input_instance': {'gaussian':        employment_years  num_open_credit_acc  annual_income loan_grade  \
    24355                 5                   12       175000.0          F

           credit_history   purpose      home addr_state
    24355            16.5  purchase  MORTGAGE         PA  },
   'time': {'gaussian': 17.315901279449463},
   'model_path': 'benchmarking_artefact/lending-club_PYT_model.pth'},
  'TF2': {'accuracy': 0.8294095396995544,
   'cfs': {'gaussian':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0               0.0                  2.0       393414.9          C
    1               0.0                  2.0       201211.3          C
    2               5.0                 26.0       157875.5          A
    3               0.0                  2.0         4080.0          C
    4               0.0                 12.0       166971.8          C

       credit_history purpose   home addr_state  loan_status
    0             3.0    debt    OWN         TN        0.397
    1            13.1    debt    OWN         TN        0.415
    2            16.5    debt  OTHER         FL        0.459
    3             3.0    debt    OWN         TN        0.385
    4             3.0    debt    OWN         TN        0.424  },
   'input_instance': {'gaussian':        employment_years  num_open_credit_acc  annual_income loan_grade  \
    24355                 5                   12       175000.0          F

           credit_history   purpose      home addr_state
    24355            16.5  purchase  MORTGAGE         PA  },
   'time': {'gaussian': 200.41499495506287},
   'model_path': 'benchmarking_artefact/lending-club_TF2_model'}},
 'german-credit': {'sklearn': {'accuracy': 0.755,
   'cfs': {'gaussian':   status_of_existing_checking_account  duration_in_month  \
    0                   0 <= ... < 200 DM                 12
    0                          ... < 0 DM                  4
    0                          ... < 0 DM                  4
    0                          ... < 0 DM                  4
    0                          ... < 0 DM                  4

                                 credit_history              purpose  \
    0  existing credits paid back duly till now  furniture/equipment
    0           delay in paying off in the past            car (new)
    0   all credits at this bank paid back duly            car (new)
    0   all credits at this bank paid back duly  domestic appliances
    0   all credits at this bank paid back duly  domestic appliances

       credit_amount savings_account_bonds present_employment_since  \
    0           1922                   A61       1 <= ... < 4 years
    0            276                   A61               unemployed
    0            276                   A61               unemployed
    0           1553                   A61            .. >= 7 years
    0            276                   A61             ... < 1 year

       installment_rate_in_percentage_of_disposable_income  \
    0                                                  4
    0                                                  4
    0                                                  4
    0                                                  4
    0                                                  4

      personal_status_and_sex other_debtors_guarantors  ...  \
    0           male : single                     none  ...
    0           male : single                guarantor  ...
    0           male : single                guarantor  ...
    0           male : single                guarantor  ...
    0  male : married/widowed             co-applicant  ...

                                                property age_in_years  \
    0  if not A121 : building society savings agreeme...           37
    0                              unknown / no property           34
    0                                        real estate           34
    0  if not A121/A122 : car or other, not in attrib...           34
    0                              unknown / no property           34

       other_installment_plans   housing number_of_existing_credits_at_this_bank  \
    0                     none       own                                       1
    0                     bank  for free                                       2
    0                   stores       own                                       1
    0                     bank      rent                                       2
    0                   stores      rent                                       2

                                                     job  \
    0                               unskilled - resident
    0  management/ self-employed/ highly qualified em...
    0                        skilled employee / official
    0                               unskilled - resident
    0                               unskilled - resident

      number_of_people_being_liable_to_provide_maintenance_for  \
    0                                                  1
    0                                                  1
    0                                                  1
    0                                                  1
    0                                                  1

                                      telephone foreign_worker credit_risk
    0                                      none            yes           1
    0                                      none            yes           1
    0  yes, registered under the customers name            yes           1
    0  yes, registered under the customers name            yes           1
    0  yes, registered under the customers name            yes           1

    [5 rows x 21 columns]},
   'input_instance': {'gaussian':     status_of_existing_checking_account  duration_in_month  \
    128                   0 <= ... < 200 DM                 12

                                            credit_history     purpose  \
    128  critical account/ other credits existing (not ...  car (used)

         credit_amount savings_account_bonds present_employment_since  \
    128           1860                   A61               unemployed

         installment_rate_in_percentage_of_disposable_income  \
    128                                                  4

        personal_status_and_sex other_debtors_guarantors  present_residence_since  \
    128           male : single                     none                        2

                                                  property  age_in_years  \
    128  if not A121/A122 : car or other, not in attrib...            34

        other_installment_plans housing  number_of_existing_credits_at_this_bank  \
    128                    none     own                                        2

                                                       job  \
    128  management/ self-employed/ highly qualified em...

         number_of_people_being_liable_to_provide_maintenance_for  \
    128                                                  1

                                        telephone foreign_worker
    128  yes, registered under the customers name            yes  },
   'time': {'gaussian': 217.61802577972412},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['credit_history', 'foreign_worker', 'housing', 'job',
          'other_debtors_guarantors', 'other_installment_plans',
          'personal_status_and_sex', 'present_employment_since', 'property',
          'purpose', 'savings_account_bonds',
          'status_of_existing_checking_account', 'telephone'],
         dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.775,
   'cfs': {'gaussian':   status_of_existing_checking_account  duration_in_month  \
    0                   0 <= ... < 200 DM                 12
    1                          ... < 0 DM                 13
    2                   0 <= ... < 200 DM                 12
    3                   0 <= ... < 200 DM                 11
    4                   0 <= ... < 200 DM                 48

                                          credit_history     purpose  \
    0  critical account/ other credits existing (not ...  car (used)
    1            all credits at this bank paid back duly    business
    2  critical account/ other credits existing (not ...     repairs
    3            all credits at this bank paid back duly  car (used)
    4  critical account/ other credits existing (not ...  car (used)

       credit_amount savings_account_bonds present_employment_since  \
    0           1847                   A61             ... < 1 year
    1           2792                   A61               unemployed
    2           1907                   A63               unemployed
    3           1868                   A61               unemployed
    4           1813                   A61               unemployed

       installment_rate_in_percentage_of_disposable_income  \
    0                                                  4
    1                                                  4
    2                                                  4
    3                                                  4
    4                                                  4

      personal_status_and_sex other_debtors_guarantors  ...  \
    0           male : single                     none  ...
    1           male : single             co-applicant  ...
    2           male : single                     none  ...
    3           male : single                     none  ...
    4           male : single                guarantor  ...

                                                property age_in_years  \
    0  if not A121/A122 : car or other, not in attrib...           34
    1  if not A121/A122 : car or other, not in attrib...           34
    2  if not A121/A122 : car or other, not in attrib...           34
    3  if not A121/A122 : car or other, not in attrib...           56
    4  if not A121/A122 : car or other, not in attrib...           34

       other_installment_plans   housing number_of_existing_credits_at_this_bank  \

In [11]:
import pickle

with open('benchmarking_final_results.pkl', 'wb') as res_file:
    pickle.dump(benchmarking.results, res_file)

## Models' accuracies on all four datasets

In [ ]:
# Accuracy table for each dataset

from IPython.display import display
import pandas as pd

accuracy_data = {
    dataset: {
        model: {
            'accuracy':  round(details['accuracy'], 2)
        }
        for model, details in models.items()
    }
    for dataset, models in benchmarking.results.items()
}

rows = []

for dataset, models in accuracy_data.items():
    for model_name, model_info in models.items():
        row = {
            'Dataset': dataset,
            'Model': model_name,
            'Accuracy': model_info.get('accuracy'),
        }
        rows.append(row)


accuracy_df = pd.DataFrame(rows)
display(accuracy_df)

              Dataset    Model  Accuracy
0   compas-recidivism  sklearn      0.57
1   compas-recidivism      PYT      0.66
2   compas-recidivism      TF2      0.65
3        adult-income  sklearn      0.82
4        adult-income      PYT      0.83
5        adult-income      TF2      0.83
6        lending-club  sklearn      0.82
7        lending-club      PYT      0.83
8        lending-club      TF2      0.83
9       german-credit  sklearn      0.76
10      german-credit      PYT      0.78
11      german-credit      TF2      0.79

## Explainers' counterfactual generation time with different datasets

In [22]:
benchmarking.results['adult-income']['PYT']['time']

{'gaussian': 7.1413209438323975}

In [ ]:
# Counterfactual generation time table
time_spent_data = {
    dataset: {
        model: {
            'time': round(details['time']['gaussian'], 2)
        }
        for model, details in models.items()
    }
    for dataset, models in benchmarking.results.items()
}

print(time_spent_data)

rows = []

for dataset, models in time_spent_data.items():
    for model_name, model_info in models.items():
        row = {
            'Dataset': dataset,
            'Model': model_name,
            'Time (ms)': model_info.get('time'),
        }
        rows.append(row)

time_df = pd.DataFrame(rows)
display(time_df)

              Dataset    Model  Time (ms)
0   compas-recidivism  sklearn      10.22
1   compas-recidivism      PYT       2.69
2   compas-recidivism      TF2      30.95
3        adult-income  sklearn      49.08
4        adult-income      PYT       7.14
5        adult-income      TF2      43.72
6        lending-club  sklearn     110.42
7        lending-club      PYT      17.32
8        lending-club      TF2     200.41
9       german-credit  sklearn     217.62
10      german-credit      PYT      10.89
11      german-credit      TF2      61.37

In [121]:
import pickle

with open("benchmarking_results_ran_w_2.pkl", "wb") as f:
    pickle.dump(benchmarking.results, f)

In [122]:
with open("benchmarking_results_ran_w_2.pkl", "rb") as f:
    b_results = pickle.load(f)

b_results

{'compas-recidivism': {'sklearn': {'accuracy': 0.5714285714285714,
   'cfs': {'gaussian':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0    Male  27.0           0.0  African-American               F             1
    0    Male  28.0           0.0  African-American               F             1
    0    Male  26.0           0.0  African-American               F             1
    0  Female  26.0           0.0         Caucasian               F             1,
    'random':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0    Male  27.0           0.0  African-American               F             1
    0  Female  18.0           0.0         Caucasian               F             1
    0    Male  18.0           0.0  African-American               F             1
    0    Male  18.0           0.0  African-American               M             1,
    'spherical':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0  Female  18.0           0.0         Caucasian               F             1
    0    Male  18.0           0.0  African-American               F             1
    0    Male  18.0           0.0  African-American               M             1},
   'input_instance': {'gaussian':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'random':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'spherical':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F},
   'time': {'gaussian': 7.876115798950195,
    'random': 39.955695152282715,
    'spherical': 177.78530883789062},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['c_charge_degree', 'race', 'sex'], dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.6629778672032193,
   'cfs': {'gaussian':       sex   age  priors_count       race c_charge_degree  twoyearrecid
    0  Female  18.0           0.0  Caucasian               M         0.547
    1  Female  21.4           8.5  Caucasian               M         0.608
    2  Female  26.3          14.0  Caucasian               F         0.571
    3  Female  18.0          21.7  Caucasian               F         0.634,
    'random':       sex   age  priors_count       race c_charge_degree  twoyearrecid
    0  Female  18.0           0.0  Caucasian               M         0.547
    1  Female  21.4           8.5  Caucasian               M         0.608
    2  Female  26.3          14.0  Caucasian               F         0.571
    3  Female  18.0          21.7  Caucasian               F         0.634,
    'spherical':       sex   age  priors_count       race c_charge_degree  twoyearrecid
    0  Female  18.0           0.0  Caucasian               M         0.547
    1  Female  21.4           8.5  Caucasian               M         0.608
    2  Female  26.3          14.0  Caucasian               F         0.571
    3  Female  18.0          21.7  Caucasian               F         0.634},
   'input_instance': {'gaussian':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'random':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'spherical':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F},
   'time': {'gaussian': 26.621819972991943,
    'random': 26.376206874847412,
    'spherical': 29.00187611579895},
   'model_path': 'benchmarking_artefact/compas-recidivism_PYT_model.pth'},
  'TF2': {'accuracy': 0.6569416522979736,
   'cfs': {'gaussian':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0  Female  26.4           1.9         Caucasian               M         0.697
    1    Male  28.8           0.0  African-American               M         0.734
    2    Male  51.5           0.0         Caucasian               M         0.733
    3    Male  26.1           7.3  African-American               M         0.730,
    'random':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0  Female  26.3           1.8         Caucasian               M         0.697
    1    Male  28.5           0.0  African-American               M         0.734
    2    Male  52.0           0.0         Caucasian               M         0.733
    3    Male  26.7           7.2  African-American               M         0.731,
    'spherical':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0  Female  26.4           1.9         Caucasian               M         0.697
    1    Male  28.8           0.0  African-American               M         0.734
    2    Male  51.5           0.0         Caucasian               M         0.733
    3    Male  26.1           7.3  African-American               M         0.730},
   'input_instance': {'gaussian':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'random':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'spherical':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F},
   'time': {'gaussian': 108.7200300693512,
    'random': 148.2435700893402,
    'spherical': 109.94285702705383},
   'model_path': 'benchmarking_artefact/compas-recidivism_TF2_model'}},
 'adult-income': {'sklearn': {'accuracy': 0.8180561953017043,
   'cfs': {'gaussian':    age      workclass     education marital_status     occupation   race  \
    0   23  Other/Unknown         Assoc        Married  Other/Unknown  White
    0   17  Other/Unknown   Prof-school         Single   White-Collar  White
    0   23  Other/Unknown  Some-college        Married  Other/Unknown  Other
    0   23        Private  Some-college        Married   White-Collar  White

      gender  hours_per_week  income
    0   Male              40       1
    0   Male              40       1
    0   Male              40       1
    0   Male              40       1  ,
    'random':    age      workclass     education marital_status     occupation   race  \
    0   17     Government         Assoc        Married          Sales  White
    0   17  Other/Unknown  Some-college        Married  Other/Unknown  Other
    0   17     Government         Assoc        Married          Sales  White

       gender  hours_per_week  income
    0  Female               1       1
    0    Male               1       1
    0    Male               1       1  ,
    'spherical':    age   workclass    education marital_status     occupation   race  gender  \
    0   17  Government  Prof-school       Divorced   White-Collar  Other    Male
    0   17  Government      Masters        Married   Professional  Other  Female
    0   17  Government        Assoc        Married    Blue-Collar  Other  Female
    0   17  Government        Assoc        Married  Other/Unknown  White    Male

       hours_per_week  income
    0               1       1
    0               1       1
    0               1       1
    0               1       1  },
   'input_instance': {'gaussian':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'random':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'spherical':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  },
   'time': {'gaussian': 43.72855091094971,
    'random': 2301.828824043274,
    'spherical': 2442.4709639549255},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['education', 'gender', 'marital_status', 'occupation', 'race',
          'workclass'],
         dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.8363273453093812,
   'cfs': {'gaussian':    age      workclass     education marital_status     occupation   race  \
    0   19  Other/Unknown  Some-college        Widowed  Other/Unknown  White
    1   20  Other/Unknown  Some-college        Widowed          Sales  White
    2   17        Private     Bachelors         Single  Other/Unknown  White
    3   36  Other/Unknown  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male              31   0.638
    1    Male              43   0.707
    2    Male              39   0.755
    3  Female              39   0.708  ,
    'random':    age      workclass     education marital_status     occupation   race  \
    0   20  Other/Unknown  Some-college        Widowed  Other/Unknown  White
    1   19  Other/Unknown  Some-college        Widowed          Sales  White
    2   17        Private     Bachelors         Single  Other/Unknown  White
    3   30  Other/Unknown  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male              30   0.640
    1    Male              44   0.706
    2    Male              39   0.755
    3  Female              41   0.703  ,
    'spherical':    age      workclass     education marital_status     occupation   race  \
    0   27  Other/Unknown  Some-college        Widowed  Other/Unknown  White
    1   21  Other/Unknown  Some-college        Widowed          Sales  White
    2   17        Private     Bachelors         Single  Other/Unknown  White
    3   32  Other/Unknown  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male              30   0.653
    1    Male              43   0.709
    2    Male              40   0.755
    3  Female              40   0.706  },
   'input_instance': {'gaussian':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'random':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'spherical':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  },
   'time': {'gaussian': 51.43463706970215,
    'random': 192.14229106903076,
    'spherical': 114.31596207618713},
   'model_path': 'benchmarking_artefact/adult-income_PYT_model.pth'},
  'TF2': {'accuracy': 0.8354061245918274,
   'cfs': {'gaussian':     age      workclass     education marital_status     occupation   race  \
    0  20.0  Self-Employed  Some-college         Single  Other/Unknown  White
    1  17.0  Other/Unknown   Prof-school         Single  Other/Unknown  White
    2  35.0     Government  Some-college         Single  Other/Unknown  White
    3  20.0  Self-Employed  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male            28.0   0.681
    1    Male            40.0   0.600
    2  Female            40.0   0.654
    3    Male            49.0   0.680  ,
    'random':     age      workclass     education marital_status     occupation   race  \
    0  20.0  Self-Employed  Some-college         Single  Other/Unknown  White
    1  17.0  Other/Unknown   Prof-school         Single  Other/Unknown  White
    2  34.0     Government  Some-college         Single  Other/Unknown  White
    3  20.0  Self-Employed  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male            28.0   0.681
    1    Male            41.0   0.601
    2  Female            40.0   0.655
    3    Male            49.0   0.680  ,
    'spherical':     age      workclass     education marital_status     occupation   race  \
    0  20.0  Self-Employed  Some-college         Single  Other/Unknown  White
    1  17.0  Other/Unknown   Prof-school         Single  Other/Unknown  White
    2  34.0     Government  Some-college         Single  Other/Unknown  White
    3  20.0  Self-Employed  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male            28.0   0.681
    1    Male            39.0   0.600
    2  Female            40.0   0.655
    3    Male            49.0   0.680  },
   'input_instance': {'gaussian':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'random':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'spherical':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  },
   'time': {'gaussian': 110.13491415977478,
    'random': 121.50076580047607,
    'spherical': 146.1793692111969},
   'model_path': 'benchmarking_artefact/adult-income_TF2_model'}},
 'lending-club': {'sklearn': {'accuracy': 0.8233664862142768,
   'cfs': {'gaussian':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 5                    8       150000.0          F
    0                 4                   12       185000.0          F
    0                 5                    9       200000.0          C
    0                 4                   12       185000.0          C

       credit_history   purpose      home addr_state  loan_status
    0            12.1  purchase  MORTGAGE         NJ            0
    0            14.2      debt  MORTGAGE         MI            0
    0            14.2      debt  MORTGAGE         OK            0
    0            14.2      debt  MORTGAGE         AK            0  ,
    'random':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 4                   12       185000.0          F
    0                 5                   10       200000.0          F
    0                 0                    2         4080.0          F
    0                 0                    2         4080.0          F

       credit_history purpose      home addr_state  loan_status
    0             3.0    debt  MORTGAGE         MI            0
    0            22.0    debt     OTHER         GA            0
    0             3.0    debt  MORTGAGE         OH            0
    0             3.0    debt     OTHER         UT            0  ,
    'spherical':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 0                    2         4080.0          E
    0                 0                    2         4080.0          F
    0                 0                    2         4080.0          E

       credit_history      purpose      home addr_state  loan_status
    0             3.0  educational       OWN         ME            0
    0             3.0     purchase  MORTGAGE         GA            0
    0             3.0         debt  MORTGAGE         AZ            0  },
   'input_instance': {'gaussian':        employment_years  num_open_credit_acc  annual_income loan_grade  \
    24355                 5                   12       175000.0          F

           credit_history   purpose      home addr_state
    24355            16.5  purchase  MORTGAGE         PA  ,
    'random':        employment_years  num_open_credit_acc  annual_income loan_grade  \
    24355                 5                   12       175000.0          F

           credit_history   purpose      home addr_state
    24355            16.5  purchase  MORTGAGE         PA  ,
    'spherical':        employment_years  num_open_credit_acc  annual_income loan_grade  \
    24355                 5                   12       175000.0          F

           credit_history   purpose      home addr_state
    24355            16.5  purchase  MORTGAGE         PA  },
   'time': {'gaussian': 492.9578649997711,
    'random': 1353.8711881637573,
    'spherical': 1704.1223900318146},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['addr_state', 'home', 'loan_grade', 'purpose'], dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.8292836459775903,
   'cfs': {'gaussian':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 0                   12       172199.7          F
    1                 0                   19       270511.9          F
    2                 0                   24        40192.1          F
    3                 0                   42       164169.6          C

       credit_history   purpose      home addr_state  loan_status
    0             3.0  purchase  MORTGAGE         VT        0.308
    1            17.6  purchase  MORTGAGE         VT        0.306
    2            15.7  purchase  MORTGAGE         VT        0.291
    3            17.2  purchase  MORTGAGE         VT        0.282  ,
    'random':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 0                   12       159322.1          F
    1                 0                   18       270972.0          F
    2                 0                   25        33969.0          F
    3                 0                   41       153983.5          C

       credit_history   purpose      home addr_state  loan_status
    0             3.0  purchase  MORTGAGE         VT        0.308
    1            16.7  purchase  MORTGAGE         VT        0.307
    2            16.4  purchase  MORTGAGE         VT        0.290
    3            18.2  purchase  MORTGAGE         VT        0.285  ,
    'spherical':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 0                   12       179524.1          F
    1                 0                   19       260808.0          F