## Introduction to the extended version of DiCE (Diverse Counterfactual Explanations)

[Mothilal et al. (2020)](https://dl.acm.org/doi/10.1145/3351095.3372850) introduce their method of generating counterfactual explanations considering _feasibility_, and _diversity_. [Guidotti and Ruggieri (2021)](https://link.springer.com/chapter/10.1007/978-3-030-88942-5_28), claim counterfactual explanations to be robust they should be similar for similar instances when they explain. In this study, in a search to improve the quality and reliability of the counterfactual explanations _robustness_ is found to be helpful and it also introduced in the optimization function.

DiCE-Extended is built upon the [DiCE (Diverse Counterfactual Explanations)](https://github.com/interpretml/DiCE) [(Mothilal et al. 2020)](https://dl.acm.org/doi/10.1145/3351095.3372850) framework by introducing a robustness term in the optimization function.

## Manipulated Optimization Function

The core enhancement in DiCE-Extended is the manipulated optimization function, designed to balance proximity, diversity, and feasibility of counterfactuals. The function is formulated as:

<a id="equation-1"></a>
\begin{equation}
\tag{1}
C(x) = \underset{c_1, ..., c_k}{\text{arg min}}
\frac{1}{2} \sum_{i=1}^{k} yloss(f(c_i), y) +
\frac{\lambda_1}{k} \sum_{i=1}^{k} dist(c_i, x) -
\lambda_2 \cdot dpp\_diversity(c_1, ..., c_k) -
\frac{\lambda_3}{k} \sum_{i=1}^{k} robustness(c_i, c_i')
\end{equation}

- **Proximity Loss**: The first term that averages the distance between generated counterfactuals and the original input ensure the counterfactuals to be as close as possible to the original input.
- **Diversity Loss**: Diversity of the counterfactual explanations is aquired by determinental point process of which loss is represented by the second term and it ensures that _k_ number of counterfactual explanations are generated.
- **Robustness Loss**: [Guidotti (2024)](https://link.springer.com/article/10.1007/s10618-022-00831-6) defines robustness as necessity of similar instances being explained by similar counterfactual explanations such that if $b(x_1)=b(x_2)=y$ then an explainer $f$ should generate counterfactuals $c_1$ and $c_2$ that are similar and can explain $x_1$ and $x_2$. The robustness term that is based on [Dice-Sørensen Coefficient](https://en.wikipedia.org/wiki/Dice-S%C3%B8rensen_coefficient), is adopted from [Bonasera and Carrizosa (2024)](
https://doi.org/10.48550/arXiv.2407.00843).

\begin{equation}
\tag{2}
Robustness(c_i, c_i') = \frac{2 * \lvert c_i \cap c_i' \rvert}{\lvert c_i \rvert + \lvert c_i' \rvert}
\end{equation}


By adjusting the weights $\lambda_1$, $\lambda_2$, $\lambda_3$ counterfactual explanations can be customised by specific needs.

## Metrics and Sensitivity Analysis for Dice Extended


### 1. Robustness Metrics

#### Dice-Sørensen Coefficient

To evaluate robustness, the Dice-Sørensen coefficient measures the similarity between counterfactuals c1 and
c2 generated for similar input instances x1 and x2:

\begin{equation}
\tag{3}
Robustness(c_1, c_2) = \frac{2 * \lvert c_1 \cap c_2 \rvert}{\lvert c_1 \rvert + \lvert c_2 \rvert}
\end{equation}

where:
- $ c_1 $ and $ c_2 $ are binary vectors,
- $ \lvert c_1 \cap c_2 \rvert $: The number of shared (overlapping) features between c1 and c2,
- $ \lvert c_1 \rvert $ and $ \lvert c_2 \rvert $: The total number of features in each counterfactual.

#### Input Perturbation and Stability

Stability under input perturbation measures the solution variance when slight perturbations are introduced
to the input instance. The procedure includes the following steps:

1) **Apply Gaussian Noise:** Perturb the input $x$ by adding Gaussian noise $\delta$ to create perturbed inputs
$x'$:

\begin{equation}
\tag{4}
x' = x + \delta, \quad \delta \sim \mathcal{N}(0, \sigma^2)
\end{equation}

where $\sigma$ is the standard deviation of the noise (e.g., $\sigma = 0.01$).

2) **Generate Counterfactuals:** Generate counterfactual explanations $c_i$ for the original input $x$ and $c_i'$ for the perturbed input $x'$.

3) **Measure Stability:** Compare counterfactuals using a distance metric, such as the Euclidean distance:

\begin{equation}
\tag{5}
Stability = \frac{1}{n} \sum_{i=1}^{n} dist(c_i, c_i')
\end{equation}

where:

\begin{equation}
\tag{6}
dist(c_i, c_i') = \sqrt{\sum_{j=1}^{d} (c_{ij} - c_{ij}')^2}
\end{equation}

$n$ is the total number of input instances, $c_i$ is the counterfactual for the original input, and $c_i'$ is the counterfactual for the perturbed input.

### 2. Counterfactual Quality Measures

#### Fidelity

Fidelity measures how often generated counterfactuals successfully change the model’s prediction:

\begin{equation}
\tag{7}
Fidelity = \frac{\sum_{i=1}^{n} \mathbf{1}(f(c_i) = y_{desired})}{n}
\end{equation}

where:

- $f$: Prediction model,
- $c_i$: Counterfactual instance,
- $y_{desired}$: Target output class,
- $n$: Total number of counterfactuals.

#### Proximity

Proximity measures the average distance between counterfactuals $c_i$ and the original inputs $x_i$:

\begin{equation}
\tag{8}
Proximity = \frac{1}{n} \sum_{i=1}^{n} dist(x_i, c_i)
\end{equation}

The Manhattan distance can be used for simplicity:

\begin{equation}
\tag{9}
dist(x_i, c_i) = \sum_{j=1}^{d} \lvert x_{ij} - c_{ij} \rvert
\end{equation}

#### Diversity

Diversity measures how dissimilar the counterfactuals $c_1, c_2, c_3,\ldots,c_k$ are among themselves:

\begin{equation}
\tag{10}
Diversity = \frac{1}{k(k-1)}\sum_{i_1}^{k}\sum_{j \neq i}^{} dist(c_i, c_j)
\end{equation}

where $k$ is the number of counterfactuals.

### 3. Sensitivity Analysis

#### Objective Function with Weights

The modified loss function in DiCE-Extended is defined as in the [equation 1](#equation-1) where:

- $yloss(f(c_i), y)$: Prediction loss for counterfactual instance $c_i$ relative to the desired outcome $y$,
- $dist(c_i, x)$: Distance metric (e.g., Euclidean or Manhattan) between the counterfactual c_i and the original input $x$,
- $dpp\_diversity(c_1,\ldots,c_k)$: Diversity loss term based on Determinantal Point Process (DPP),
- $Robustness(c_i,c_i')$: Robustness loss measuring similarity of counterfactuals under perturbations.

  The weights $\lambda_1, \lambda_2, \lambda_3$ control the balance between proximity, diversity, and robustness, respectively.

#### Sensitivity Analysis

To perform sensitivity analysis:

1) Vary the weights $\lambda_1, \lambda_2, \lambda_3$ systematically while ensuring:

\begin{equation}
\tag{11}
\lambda_1 + \lambda_2 + \lambda_3 = 1 (for normalization).
\end{equation}

2) Track the changes in the following metrics:

\begin{equation}
\tag{12}
P(\lambda_1, \lambda_2, \lambda_3) = Proximity,
\end{equation}

\begin{equation}
\tag{13}
D(\lambda_1, \lambda_2, \lambda_3) = Diversity,
\end{equation}

\begin{equation}
\tag{14}
R(\lambda_1, \lambda_2, \lambda_3) = Robustness,
\end{equation}

3) Measure the relationship between these metrics and the weights.

In [33]:
import sys
dice_path = "/Users/volk/Documents/bau24-25/thesis/repos/DiCE-X"
sys.path.insert(0, dice_path)

In [34]:
from dice_ml_x.utils import helpers

In [35]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [120]:
from dice_ml_x.benchmarking import Benchmarking
datasets = ["compas-recidivism", "adult-income", "lending-club", "german-credit"]
backends = ["sklearn", "PYT", "TF2"]
methods = ['gaussian', 'random', 'spherical']
benchmarking = Benchmarking(datasets=datasets,
                            backends=backends,
                            perturbation_methods=methods)
benchmarking.load_and_train(batch_size=16)

""" At the end of the load and train process a dictionary containing the training and counterfactual
generation history is saved following object can be found in the results object:
"""

Benchmarking:   0%|          | 0/12 [00:00<?, ?it/s]

the dataset is : compas-recidivism, the backend is : sklearn, the method is gaussian

100%|██████████| 1/1 [00:07<00:00,  7.87s/it]

the dataset is : compas-recidivism, the backend is : sklearn, the method is random

100%|██████████| 1/1 [00:39<00:00, 39.95s/it]

the dataset is : compas-recidivism, the backend is : sklearn, the method is spherical

100%|██████████| 1/1 [02:57<00:00, 177.78s/it]
Benchmarking:   8%|▊         | 1/12 [03:45<41:23, 225.81s/it, dataset=compas-recidivism, backend=sklearn, method=spherical]

the dataset is : compas-recidivism, the backend is : PYT, the method is gaussian

100%|██████████| 1/1 [00:26<00:00, 26.62s/it]

Diverse Counterfactuals found! total time taken: 00 min 26 sec
the dataset is : compas-recidivism, the backend is : PYT, the method is random

100%|██████████| 1/1 [00:26<00:00, 26.37s/it]

Diverse Counterfactuals found! total time taken: 00 min 26 sec
the dataset is : compas-recidivism, the backend is : PYT, the method is spherical

100%|██████████| 1/1 [00:28<00:00, 29.00s/it]
Benchmarking:  17%|█▋        | 2/12 [05:08<23:38, 141.84s/it, dataset=compas-recidivism, backend=PYT, method=spherical]

Diverse Counterfactuals found! total time taken: 00 min 28 sec
the dataset is : compas-recidivism, the backend is : TF2, the method is gaussian
Diverse Counterfactuals found! total time taken: 01 min 48 sec
the dataset is : compas-recidivism, the backend is : TF2, the method is random
Diverse Counterfactuals found! total time taken: 02 min 27 sec
the dataset is : compas-recidivism, the backend is : TF2, the method is spherical

Benchmarking:  25%|██▌       | 3/12 [11:17<36:46, 245.20s/it, dataset=compas-recidivism, backend=TF2, method=spherical]

Diverse Counterfactuals found! total time taken: 01 min 49 sec
the dataset is : adult-income, the backend is : sklearn, the method is gaussian

100%|██████████| 1/1 [00:43<00:00, 43.73s/it]

the dataset is : adult-income, the backend is : sklearn, the method is random

100%|██████████| 1/1 [38:21<00:00, 2301.83s/it]

the dataset is : adult-income, the backend is : sklearn, the method is spherical

100%|██████████| 1/1 [40:42<00:00, 2442.47s/it]
Benchmarking:  33%|███▎      | 4/12 [1:31:08<4:32:00, 2040.04s/it, dataset=adult-income, backend=sklearn, method=spherical]

the dataset is : adult-income, the backend is : PYT, the method is gaussian

100%|██████████| 1/1 [00:51<00:00, 51.43s/it]

Diverse Counterfactuals found! total time taken: 00 min 51 sec
the dataset is : adult-income, the backend is : PYT, the method is random

100%|██████████| 1/1 [03:12<00:00, 192.14s/it]

Diverse Counterfactuals found! total time taken: 03 min 11 sec
the dataset is : adult-income, the backend is : PYT, the method is spherical

100%|██████████| 1/1 [01:54<00:00, 114.31s/it]
Benchmarking:  42%|████▏     | 5/12 [1:37:13<2:47:31, 1435.94s/it, dataset=adult-income, backend=PYT, method=spherical]

Diverse Counterfactuals found! total time taken: 01 min 54 sec
the dataset is : adult-income, the backend is : TF2, the method is gaussian
Diverse Counterfactuals found! total time taken: 01 min 50 sec
the dataset is : adult-income, the backend is : TF2, the method is random
Diverse Counterfactuals found! total time taken: 02 min 01 sec
the dataset is : adult-income, the backend is : TF2, the method is spherical

Benchmarking:  50%|█████     | 6/12 [1:43:39<1:47:54, 1079.06s/it, dataset=adult-income, backend=TF2, method=spherical]

Diverse Counterfactuals found! total time taken: 02 min 26 sec
the dataset is : lending-club, the backend is : sklearn, the method is gaussian

100%|██████████| 1/1 [08:12<00:00, 492.95s/it]

the dataset is : lending-club, the backend is : sklearn, the method is random

100%|██████████| 1/1 [22:33<00:00, 1353.87s/it]

the dataset is : lending-club, the backend is : sklearn, the method is spherical

100%|██████████| 1/1 [28:24<00:00, 1704.12s/it]
Benchmarking:  58%|█████▊    | 7/12 [2:42:55<2:37:23, 1888.71s/it, dataset=lending-club, backend=sklearn, method=spherical]

the dataset is : lending-club, the backend is : PYT, the method is gaussian

100%|██████████| 1/1 [03:50<00:00, 230.76s/it]

Diverse Counterfactuals found! total time taken: 02 min 01 sec
the dataset is : lending-club, the backend is : PYT, the method is random

100%|██████████| 1/1 [04:59<00:00, 299.96s/it]

Diverse Counterfactuals found! total time taken: 04 min 59 sec
the dataset is : lending-club, the backend is : PYT, the method is spherical

100%|██████████| 1/1 [06:08<00:00, 368.61s/it]
Benchmarking:  67%|██████▋   | 8/12 [2:58:03<1:45:05, 1576.46s/it, dataset=lending-club, backend=PYT, method=spherical]

Diverse Counterfactuals found! total time taken: 06 min 08 sec
the dataset is : lending-club, the backend is : TF2, the method is gaussian
Diverse Counterfactuals found! total time taken: 01 min 53 sec
the dataset is : lending-club, the backend is : TF2, the method is random
Diverse Counterfactuals found! total time taken: 07 min 44 sec
the dataset is : lending-club, the backend is : TF2, the method is spherical

Benchmarking:  75%|███████▌  | 9/12 [3:14:29<1:09:36, 1392.03s/it, dataset=lending-club, backend=TF2, method=spherical]

Diverse Counterfactuals found! total time taken: 04 min 45 sec
the dataset is : german-credit, the backend is : sklearn, the method is gaussian

100%|██████████| 1/1 [02:02<00:00, 122.05s/it]

the dataset is : german-credit, the backend is : sklearn, the method is random

100%|██████████| 1/1 [1:06:11<00:00, 3971.73s/it]

the dataset is : german-credit, the backend is : sklearn, the method is spherical

100%|██████████| 1/1 [1:09:18<00:00, 4158.37s/it]
Benchmarking:  83%|████████▎ | 10/12 [5:32:02<1:56:59, 3509.96s/it, dataset=german-credit, backend=sklearn, method=spherical]

the dataset is : german-credit, the backend is : PYT, the method is gaussian

WARNING:root: MAD for feature number_of_existing_credits_at_this_bank is 0, so replacing it with 1.0 to avoid error.
WARNING:root: MAD for feature number_of_people_being_liable_to_provide_maintenance_for is 0, so replacing it with 1.0 to avoid error.
100%|██████████| 1/1 [02:59<00:00, 179.22s/it]

Diverse Counterfactuals found! total time taken: 02 min 55 sec
the dataset is : german-credit, the backend is : PYT, the method is random

WARNING:root: MAD for feature number_of_existing_credits_at_this_bank is 0, so replacing it with 1.0 to avoid error.
WARNING:root: MAD for feature number_of_people_being_liable_to_provide_maintenance_for is 0, so replacing it with 1.0 to avoid error.
100%|██████████| 1/1 [04:26<00:00, 266.62s/it]

Diverse Counterfactuals found! total time taken: 04 min 23 sec
the dataset is : german-credit, the backend is : PYT, the method is spherical

WARNING:root: MAD for feature number_of_existing_credits_at_this_bank is 0, so replacing it with 1.0 to avoid error.
WARNING:root: MAD for feature number_of_people_being_liable_to_provide_maintenance_for is 0, so replacing it with 1.0 to avoid error.
100%|██████████| 1/1 [04:42<00:00, 282.78s/it]
Benchmarking:  92%|█████████▏| 11/12 [5:44:11<44:18, 2658.83s/it, dataset=german-credit, backend=PYT, method=spherical]

Diverse Counterfactuals found! total time taken: 04 min 40 sec

WARNING:root: MAD for feature number_of_existing_credits_at_this_bank is 0, so replacing it with 1.0 to avoid error.
WARNING:root: MAD for feature number_of_people_being_liable_to_provide_maintenance_for is 0, so replacing it with 1.0 to avoid error.

the dataset is : german-credit, the backend is : TF2, the method is gaussian

WARNING:root: MAD for feature number_of_existing_credits_at_this_bank is 0, so replacing it with 1.0 to avoid error.
WARNING:root: MAD for feature number_of_people_being_liable_to_provide_maintenance_for is 0, so replacing it with 1.0 to avoid error.

Diverse Counterfactuals found! total time taken: 04 min 42 sec
the dataset is : german-credit, the backend is : TF2, the method is random

WARNING:root: MAD for feature number_of_existing_credits_at_this_bank is 0, so replacing it with 1.0 to avoid error.
WARNING:root: MAD for feature number_of_people_being_liable_to_provide_maintenance_for is 0, so replacing it with 1.0 to avoid error.

Diverse Counterfactuals found! total time taken: 06 min 31 sec
the dataset is : german-credit, the backend is : TF2, the method is spherical

Benchmarking: 100%|██████████| 12/12 [6:12:56<00:00, 1864.69s/it, dataset=german-credit, backend=TF2, method=spherical]

Diverse Counterfactuals found! total time taken: 17 min 21 sec

' At the end of the load and train process a dictionary containing the training and counterfactual\ngeneration history is saved following object can be found in the results object:\n'

In [123]:
print(f"Model accuracy is {benchmarking.results['compas-recidivism']['PYT']['accuracy']} on the test dataset.")

Model accuracy is 0.6629778672032193 on the test dataset.

In [86]:
from IPython.display import display

original_instance = benchmarking.results['german-credit']['PYT']['input_instance']['gaussian']
gaussian_cfs = benchmarking.results['german-credit']['PYT']['cfs']['gaussian']

display(original_instance)
display(gaussian_cfs)

,status_of_existing_checking_account,duration_in_month,credit_history,purpose,credit_amount,savings_account_bonds,present_employment_since,installment_rate_in_percentage_of_disposable_income,personal_status_and_sex,other_debtors_guarantors,present_residence_since,property,age_in_years,other_installment_plans,housing,number_of_existing_credits_at_this_bank,job,number_of_people_being_liable_to_provide_maintenance_for,telephone,foreign_worker
128,0 <= ... < 200 DM,12,critical account/ other credits existing (not ...,car (used),1860,A61,unemployed,4,male : single,none,2,"if not A121/A122 : car or other, not in attrib...",34,none,own,2,management/ self-employed/ highly qualified em...,1,"yes, registered under the customers name",yes

,status_of_existing_checking_account,duration_in_month,credit_history,purpose,credit_amount,savings_account_bonds,present_employment_since,installment_rate_in_percentage_of_disposable_income,personal_status_and_sex,other_debtors_guarantors,...,property,age_in_years,other_installment_plans,housing,number_of_existing_credits_at_this_bank,job,number_of_people_being_liable_to_provide_maintenance_for,telephone,foreign_worker,credit_risk
0,0 <= ... < 200 DM,12,all credits at this bank paid back duly,business,2071,A61,unemployed,4,male : single,guarantor,...,"if not A121/A122 : car or other, not in attrib...",24,none,own,2,unemployed/ unskilled - non-resident,1,"yes, registered under the customers name",yes,0.765
1,no checking account,12,delay in paying off in the past,car (used),1828,A61,unemployed,4,male : single,co-applicant,...,"if not A121/A122 : car or other, not in attrib...",34,none,own,2,unemployed/ unskilled - non-resident,1,"yes, registered under the customers name",no,0.701
2,0 <= ... < 200 DM,12,delay in paying off in the past,car (used),1733,A63,... < 1 year,4,male : single,none,...,"if not A121/A122 : car or other, not in attrib...",34,none,own,2,unemployed/ unskilled - non-resident,1,none,yes,0.725
3,0 <= ... < 200 DM,18,all credits at this bank paid back duly,car (used),1786,A61,unemployed,4,male : single,guarantor,...,"if not A121/A122 : car or other, not in attrib...",34,none,for free,4,management/ self-employed/ highly qualified em...,1,none,yes,0.744

In [121]:
import pickle

with open("benchmarking_results_ran_w_2.pkl", "wb") as f:
    pickle.dump(benchmarking.results, f)

In [122]:
with open("benchmarking_results_ran_w_2.pkl", "rb") as f:
    b_results = pickle.load(f)

b_results

{'compas-recidivism': {'sklearn': {'accuracy': 0.5714285714285714,
   'cfs': {'gaussian':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0    Male  27.0           0.0  African-American               F             1
    0    Male  28.0           0.0  African-American               F             1
    0    Male  26.0           0.0  African-American               F             1
    0  Female  26.0           0.0         Caucasian               F             1,
    'random':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0    Male  27.0           0.0  African-American               F             1
    0  Female  18.0           0.0         Caucasian               F             1
    0    Male  18.0           0.0  African-American               F             1
    0    Male  18.0           0.0  African-American               M             1,
    'spherical':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0  Female  18.0           0.0         Caucasian               F             1
    0    Male  18.0           0.0  African-American               F             1
    0    Male  18.0           0.0  African-American               M             1},
   'input_instance': {'gaussian':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'random':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'spherical':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F},
   'time': {'gaussian': 7.876115798950195,
    'random': 39.955695152282715,
    'spherical': 177.78530883789062},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['c_charge_degree', 'race', 'sex'], dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.6629778672032193,
   'cfs': {'gaussian':       sex   age  priors_count       race c_charge_degree  twoyearrecid
    0  Female  18.0           0.0  Caucasian               M         0.547
    1  Female  21.4           8.5  Caucasian               M         0.608
    2  Female  26.3          14.0  Caucasian               F         0.571
    3  Female  18.0          21.7  Caucasian               F         0.634,
    'random':       sex   age  priors_count       race c_charge_degree  twoyearrecid
    0  Female  18.0           0.0  Caucasian               M         0.547
    1  Female  21.4           8.5  Caucasian               M         0.608
    2  Female  26.3          14.0  Caucasian               F         0.571
    3  Female  18.0          21.7  Caucasian               F         0.634,
    'spherical':       sex   age  priors_count       race c_charge_degree  twoyearrecid
    0  Female  18.0           0.0  Caucasian               M         0.547
    1  Female  21.4           8.5  Caucasian               M         0.608
    2  Female  26.3          14.0  Caucasian               F         0.571
    3  Female  18.0          21.7  Caucasian               F         0.634},
   'input_instance': {'gaussian':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'random':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'spherical':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F},
   'time': {'gaussian': 26.621819972991943,
    'random': 26.376206874847412,
    'spherical': 29.00187611579895},
   'model_path': 'benchmarking_artefact/compas-recidivism_PYT_model.pth'},
  'TF2': {'accuracy': 0.6569416522979736,
   'cfs': {'gaussian':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0  Female  26.4           1.9         Caucasian               M         0.697
    1    Male  28.8           0.0  African-American               M         0.734
    2    Male  51.5           0.0         Caucasian               M         0.733
    3    Male  26.1           7.3  African-American               M         0.730,
    'random':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0  Female  26.3           1.8         Caucasian               M         0.697
    1    Male  28.5           0.0  African-American               M         0.734
    2    Male  52.0           0.0         Caucasian               M         0.733
    3    Male  26.7           7.2  African-American               M         0.731,
    'spherical':       sex   age  priors_count              race c_charge_degree  twoyearrecid
    0  Female  26.4           1.9         Caucasian               M         0.697
    1    Male  28.8           0.0  African-American               M         0.734
    2    Male  51.5           0.0         Caucasian               M         0.733
    3    Male  26.1           7.3  African-American               M         0.730},
   'input_instance': {'gaussian':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'random':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F,
    'spherical':        sex   age  priors_count       race c_charge_degree
    4096  Male  27.0           0.0  Caucasian               F},
   'time': {'gaussian': 108.7200300693512,
    'random': 148.2435700893402,
    'spherical': 109.94285702705383},
   'model_path': 'benchmarking_artefact/compas-recidivism_TF2_model'}},
 'adult-income': {'sklearn': {'accuracy': 0.8180561953017043,
   'cfs': {'gaussian':    age      workclass     education marital_status     occupation   race  \
    0   23  Other/Unknown         Assoc        Married  Other/Unknown  White
    0   17  Other/Unknown   Prof-school         Single   White-Collar  White
    0   23  Other/Unknown  Some-college        Married  Other/Unknown  Other
    0   23        Private  Some-college        Married   White-Collar  White

      gender  hours_per_week  income
    0   Male              40       1
    0   Male              40       1
    0   Male              40       1
    0   Male              40       1  ,
    'random':    age      workclass     education marital_status     occupation   race  \
    0   17     Government         Assoc        Married          Sales  White
    0   17  Other/Unknown  Some-college        Married  Other/Unknown  Other
    0   17     Government         Assoc        Married          Sales  White

       gender  hours_per_week  income
    0  Female               1       1
    0    Male               1       1
    0    Male               1       1  ,
    'spherical':    age   workclass    education marital_status     occupation   race  gender  \
    0   17  Government  Prof-school       Divorced   White-Collar  Other    Male
    0   17  Government      Masters        Married   Professional  Other  Female
    0   17  Government        Assoc        Married    Blue-Collar  Other  Female
    0   17  Government        Assoc        Married  Other/Unknown  White    Male

       hours_per_week  income
    0               1       1
    0               1       1
    0               1       1
    0               1       1  },
   'input_instance': {'gaussian':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'random':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'spherical':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  },
   'time': {'gaussian': 43.72855091094971,
    'random': 2301.828824043274,
    'spherical': 2442.4709639549255},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['education', 'gender', 'marital_status', 'occupation', 'race',
          'workclass'],
         dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.8363273453093812,
   'cfs': {'gaussian':    age      workclass     education marital_status     occupation   race  \
    0   19  Other/Unknown  Some-college        Widowed  Other/Unknown  White
    1   20  Other/Unknown  Some-college        Widowed          Sales  White
    2   17        Private     Bachelors         Single  Other/Unknown  White
    3   36  Other/Unknown  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male              31   0.638
    1    Male              43   0.707
    2    Male              39   0.755
    3  Female              39   0.708  ,
    'random':    age      workclass     education marital_status     occupation   race  \
    0   20  Other/Unknown  Some-college        Widowed  Other/Unknown  White
    1   19  Other/Unknown  Some-college        Widowed          Sales  White
    2   17        Private     Bachelors         Single  Other/Unknown  White
    3   30  Other/Unknown  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male              30   0.640
    1    Male              44   0.706
    2    Male              39   0.755
    3  Female              41   0.703  ,
    'spherical':    age      workclass     education marital_status     occupation   race  \
    0   27  Other/Unknown  Some-college        Widowed  Other/Unknown  White
    1   21  Other/Unknown  Some-college        Widowed          Sales  White
    2   17        Private     Bachelors         Single  Other/Unknown  White
    3   32  Other/Unknown  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male              30   0.653
    1    Male              43   0.709
    2    Male              40   0.755
    3  Female              40   0.706  },
   'input_instance': {'gaussian':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'random':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'spherical':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  },
   'time': {'gaussian': 51.43463706970215,
    'random': 192.14229106903076,
    'spherical': 114.31596207618713},
   'model_path': 'benchmarking_artefact/adult-income_PYT_model.pth'},
  'TF2': {'accuracy': 0.8354061245918274,
   'cfs': {'gaussian':     age      workclass     education marital_status     occupation   race  \
    0  20.0  Self-Employed  Some-college         Single  Other/Unknown  White
    1  17.0  Other/Unknown   Prof-school         Single  Other/Unknown  White
    2  35.0     Government  Some-college         Single  Other/Unknown  White
    3  20.0  Self-Employed  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male            28.0   0.681
    1    Male            40.0   0.600
    2  Female            40.0   0.654
    3    Male            49.0   0.680  ,
    'random':     age      workclass     education marital_status     occupation   race  \
    0  20.0  Self-Employed  Some-college         Single  Other/Unknown  White
    1  17.0  Other/Unknown   Prof-school         Single  Other/Unknown  White
    2  34.0     Government  Some-college         Single  Other/Unknown  White
    3  20.0  Self-Employed  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male            28.0   0.681
    1    Male            41.0   0.601
    2  Female            40.0   0.655
    3    Male            49.0   0.680  ,
    'spherical':     age      workclass     education marital_status     occupation   race  \
    0  20.0  Self-Employed  Some-college         Single  Other/Unknown  White
    1  17.0  Other/Unknown   Prof-school         Single  Other/Unknown  White
    2  34.0     Government  Some-college         Single  Other/Unknown  White
    3  20.0  Self-Employed  Some-college         Single  Other/Unknown  Other

       gender  hours_per_week  income
    0    Male            28.0   0.681
    1    Male            39.0   0.600
    2  Female            40.0   0.655
    3    Male            49.0   0.680  },
   'input_instance': {'gaussian':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'random':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  ,
    'spherical':        age      workclass     education marital_status     occupation   race  \
    25134   20  Other/Unknown  Some-college         Single  Other/Unknown  White

          gender  hours_per_week
    25134   Male              40  },
   'time': {'gaussian': 110.13491415977478,
    'random': 121.50076580047607,
    'spherical': 146.1793692111969},
   'model_path': 'benchmarking_artefact/adult-income_TF2_model'}},
 'lending-club': {'sklearn': {'accuracy': 0.8233664862142768,
   'cfs': {'gaussian':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 5                    8       150000.0          F
    0                 4                   12       185000.0          F
    0                 5                    9       200000.0          C
    0                 4                   12       185000.0          C

       credit_history   purpose      home addr_state  loan_status
    0            12.1  purchase  MORTGAGE         NJ            0
    0            14.2      debt  MORTGAGE         MI            0
    0            14.2      debt  MORTGAGE         OK            0
    0            14.2      debt  MORTGAGE         AK            0  ,
    'random':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 4                   12       185000.0          F
    0                 5                   10       200000.0          F
    0                 0                    2         4080.0          F
    0                 0                    2         4080.0          F

       credit_history purpose      home addr_state  loan_status
    0             3.0    debt  MORTGAGE         MI            0
    0            22.0    debt     OTHER         GA            0
    0             3.0    debt  MORTGAGE         OH            0
    0             3.0    debt     OTHER         UT            0  ,
    'spherical':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 0                    2         4080.0          E
    0                 0                    2         4080.0          F
    0                 0                    2         4080.0          E

       credit_history      purpose      home addr_state  loan_status
    0             3.0  educational       OWN         ME            0
    0             3.0     purchase  MORTGAGE         GA            0
    0             3.0         debt  MORTGAGE         AZ            0  },
   'input_instance': {'gaussian':        employment_years  num_open_credit_acc  annual_income loan_grade  \
    24355                 5                   12       175000.0          F

           credit_history   purpose      home addr_state
    24355            16.5  purchase  MORTGAGE         PA  ,
    'random':        employment_years  num_open_credit_acc  annual_income loan_grade  \
    24355                 5                   12       175000.0          F

           credit_history   purpose      home addr_state
    24355            16.5  purchase  MORTGAGE         PA  ,
    'spherical':        employment_years  num_open_credit_acc  annual_income loan_grade  \
    24355                 5                   12       175000.0          F

           credit_history   purpose      home addr_state
    24355            16.5  purchase  MORTGAGE         PA  },
   'time': {'gaussian': 492.9578649997711,
    'random': 1353.8711881637573,
    'spherical': 1704.1223900318146},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['addr_state', 'home', 'loan_grade', 'purpose'], dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.8292836459775903,
   'cfs': {'gaussian':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 0                   12       172199.7          F
    1                 0                   19       270511.9          F
    2                 0                   24        40192.1          F
    3                 0                   42       164169.6          C

       credit_history   purpose      home addr_state  loan_status
    0             3.0  purchase  MORTGAGE         VT        0.308
    1            17.6  purchase  MORTGAGE         VT        0.306
    2            15.7  purchase  MORTGAGE         VT        0.291
    3            17.2  purchase  MORTGAGE         VT        0.282  ,
    'random':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 0                   12       159322.1          F
    1                 0                   18       270972.0          F
    2                 0                   25        33969.0          F
    3                 0                   41       153983.5          C

       credit_history   purpose      home addr_state  loan_status
    0             3.0  purchase  MORTGAGE         VT        0.308
    1            16.7  purchase  MORTGAGE         VT        0.307
    2            16.4  purchase  MORTGAGE         VT        0.290
    3            18.2  purchase  MORTGAGE         VT        0.285  ,
    'spherical':    employment_years  num_open_credit_acc  annual_income loan_grade  \
    0                 0                   12       179524.1          F
    1                 0                   19       260808.0          F